remote_theme: just-the-docs/just-the-docs@v0.8.0
title: Token of Exchange
description: Heterodox economic insights through the eyes of an Engineer and Software Developer
# plus mahdolliset asetukset jotka just-the-docs tukee (esim. navigaatio, layout)
author:
  name: Mikko Sipola — 2025
  email: "mikko.sipola@tutanota.com"
