remote_theme: "jekyll/minima@1e8a445"
title: Token of Exchange
description: Heterodox economic insights through the eyes of an Engineer and Software Developer
minima:
  nav_pages:
    - index.md
    - iterations.md
minima: 
  skin: solarized-dark
author:
  name: Mikko Sipola — 2025
  email: "mikko.sipola@tutanota.com"