remote_theme: "jekyll/minima@1e8a445"
title: Heterodox economics
description: ...from the the viewpoint of an Engineer and Software Developer
minima:
  nav_pages:
    - index.md
    - ToE-requirements.md
minima:
  skin: solarized-dark
author:
  name: Mikko Sipola 2025
  email: "mikko.sipola@tutanota.com"