remote_theme: "pages-themes/slate@v0.2.0"
title: Token of Exchange
description: Heterodox economic insights through the eyes of an Engineer and Software Developer
author:
  name: Mikko Sipola — 2025
  email: "mikko.sipola@tutanota.com"